# Generated by Django 5.0.7 on 2024-07-20 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Price",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=7, verbose_name="Стартовая цена"
                    ),
                ),
                (
                    "goods",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Товар"
                    ),
                ),
                (
                    "taxes",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.06,
                        max_digits=6,
                        verbose_name="Общие налоги",
                    ),
                ),
                (
                    "bank_taxes",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.02,
                        max_digits=6,
                        verbose_name="Отчисления банку",
                    ),
                ),
                (
                    "seller_taxes",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.12,
                        max_digits=7,
                        verbose_name="Отчисления продавцу",
                    ),
                ),
                (
                    "self_profit",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.2,
                        max_digits=7,
                        verbose_name="Отчисления магазину",
                    ),
                ),
                (
                    "total_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=8,
                        null=True,
                        verbose_name="Итоговая цена",
                    ),
                ),
            ],
            options={
                "verbose_name": "Цена",
                "verbose_name_plural": "Цены",
            },
        ),
    ]
