# Generated by Django 5.0.7 on 2024-07-20 08:53

from decimal import Decimal

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("price", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="price",
            name="taxes",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.06"),
                max_digits=6,
                verbose_name="Общие налоги",
            ),
        ),
    ]
